package com.villagertradepredicator.core;

import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.villagertradepredicator.core.data.LoadedTradeSet;
import com.villagertradepredicator.core.data.TradeDataRepository;
import com.villagertradepredicator.core.locate.RoundIterator;
import com.villagertradepredicator.core.model.PredictedOffer;
import com.villagertradepredicator.core.model.TradeSetDef;
import com.villagertradepredicator.core.rng.SequenceConfig;
import com.villagertradepredicator.core.rng.TradeSequences;
import com.villagertradepredicator.core.sim.SimContext;
import net.minecraft.resources.Identifier;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Full-matrix cross-validation against the author's validated CLI predictor (option 1 of
 * the verification plan): 3 random seeds x all 13 professions x 5 levels x 2 offsets =
 * 390 cells, generated by {@code scripts/gen_golden_matrix.py} from the 26.1 data the
 * CLI models.
 *
 * <p>Cells are verified according to their semantic tier:
 * <ul>
 *   <li><b>EXACT</b> — compatible set without variant predicates whose runtime pool order
 *       equals the fixture's (26.1) order: Java tokens must equal the CLI output
 *       token-for-token.</li>
 *   <li><b>POOL_REORDERED</b> — same pool members but 26.2 reordered them relative to
 *       26.1; {@code nextInt(bound)} maps positions, so the CLI fixture simply does not
 *       apply to the 26.2 runtime. Determinism is asserted; these cells exact-match when
 *       the suite runs on the 26.1.2 node (asserted there).</li>
 *   <li><b>VARIANT</b> — compatible set whose pool contains villager/variant predicates:
 *       the CLI has no variant input and its pre-filter semantics diverge from vanilla,
 *       so only determinism is asserted (correctness anchored by the vanilla-semantics
 *       implementation + planned GameTest).</li>
 *   <li><b>DISABLED</b> — set the compatibility gate refuses (unsupported modifiers such
 *       as {@code enchant_with_levels}/{@code exploration_map}); these cells assert the
 *       gate's verdict instead of values.</li>
 * </ul></p>
 */
class PythonMatrixParityTest {
    private static TradeDataRepository repo;
    private static JsonArray cells;
    private static Map<String, List<String>> fixturePools;

    private int exact;
    private int poolReordered;
    private int variant;
    private int disabled;

    @BeforeAll
    static void setup() throws Exception {
        TestSupport.bootstrap();
        repo = TradeDataRepository.loadFromClasspath();
        try (InputStreamReader reader = new InputStreamReader(
                PythonMatrixParityTest.class.getResourceAsStream("/golden_matrix.json"),
                java.nio.charset.StandardCharsets.UTF_8)) {
            JsonObject root = JsonParser.parseReader(reader).getAsJsonObject();
            cells = root.getAsJsonArray("cells");
            fixturePools = new HashMap<>();
            for (Map.Entry<String, JsonElement> e : root.getAsJsonObject("pools").entrySet()) {
                List<String> ids = new ArrayList<>();
                for (JsonElement id : e.getValue().getAsJsonArray()) {
                    ids.add(id.getAsString());
                }
                fixturePools.put(e.getKey(), ids);
            }
        }
    }

    private static List<String> describe(long seed, Identifier profession, int level, int offset) {
        Optional<TradeSetDef> set = repo.compatible(profession, level);
        assertTrue(set.isPresent(), profession + " L" + level + " not compatible");
        RoundIterator it = new RoundIterator(set.get(),
                TradeSequences.create(seed, SequenceConfig.DEFAULT,
                        TradeSequences.sequenceId(profession, level)),
                SimContext.withoutVariant());
        for (int i = 0; i < offset; i++) {
            it.next();
        }
        List<String> tokens = new ArrayList<>();
        for (PredictedOffer offer : it.next().offers()) {
            tokens.add(offer.storedEnchantment()
                    .map(e -> "book:" + e.enchantment().getPath() + ":" + e.level() + ":" + offer.costA())
                    .orElseGet(offer.tradeId()::toString));
        }
        return tokens;
    }

    private static boolean hasVariantPredicate(LoadedTradeSet set) {
        return set.def().orElseThrow().trades().stream().anyMatch(t -> t.predicate().isPresent());
    }

    private static boolean runtimePoolMatchesFixture(Identifier profession, int level) {
        List<String> runtime = new ArrayList<>();
        repo.compatible(profession, level).orElseThrow().trades()
                .forEach(t -> runtime.add(t.id().toString()));
        return runtime.equals(fixturePools.get(profession.getPath() + "/" + level));
    }

    @Test
    void matrixMatchesPythonPredictor() {
        List<String> failures = new ArrayList<>();
        for (JsonElement element : cells) {
            JsonObject cell = element.getAsJsonObject();
            long seed = cell.get("seed").getAsLong();
            Identifier profession = Identifier.withDefaultNamespace(cell.get("profession").getAsString());
            int level = cell.get("level").getAsInt();
            int offset = cell.get("offset").getAsInt();
            List<String> expected = new ArrayList<>();
            for (JsonElement e : cell.getAsJsonArray("expected")) {
                expected.add(e.getAsString());
            }

            LoadedTradeSet set = repo.get(profession, level).orElseThrow();
            if (!set.isCompatible()) {
                disabled++;
                assertFalse(set.issues().isEmpty(), profession + " L" + level + " missing issues");
            } else if (hasVariantPredicate(set)) {
                variant++;
                assertEquals(describe(seed, profession, level, offset),
                        describe(seed, profession, level, offset), profession + " L" + level);
            } else if (!runtimePoolMatchesFixture(profession, level)) {
                poolReordered++;
                assertEquals(describe(seed, profession, level, offset),
                        describe(seed, profession, level, offset), profession + " L" + level);
            } else {
                exact++;
                List<String> actual = describe(seed, profession, level, offset);
                if (!expected.equals(actual)) {
                    failures.add("%s %s L%d off%d%n  expected %s%n  actual   %s"
                            .formatted(seed, profession, level, offset, expected, actual));
                }
            }
        }

        System.out.printf("matrix tiers: exact=%d poolReordered=%d variant=%d disabled=%d, mismatches=%d%n",
                exact, poolReordered, variant, disabled, failures.size());
        assertEquals(390, exact + poolReordered + variant + disabled, "cell count");
        assertTrue(exact >= 100, "exact tier unexpectedly small: " + exact);
        assertTrue(failures.isEmpty(), String.join("%n", failures));
    }
}
